--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HmmHmmmm/QuestPlugin
build-by-default: true
branches:
- master
projects:
  QuestPlugin:
    path: ""
    icon: "images/icon.png"
    libs:
    - src: thebigsmilexd/customui/customui
      version: ^3.0.0
    - src: poggit/libasynql/libasynql
      version: ^3.2.0
...
